### PR TITLE
add upvote and downvote for article

### PR DESCRIPTION
**Pull request by ELR143**

### CODE REVIEW

**Review by popatre — CHANGES_REQUESTED** [review]
Hello, the voting doesnt seem to actually work. 

- [x] Refresh the page and the votes havent persisted
- [x] When offline, i get no message to say it hasnt worked

https://jam.dev/c/281d0f37-309e-4a79-8270-54a95118452c

**Review by popatre — CHANGES_REQUESTED** [review]
Some good stuff in here, but a few things to change:

- [x] Consider optimistic rendering. On a slow connection, theres a massive delay and i might end up clicking the button a lot thinking it doesnt work
- [x] If you click offline, you get the error, but this then appears even when successful after this. 
- [x] The error seems quite specific to being offline, but there could also be a server error. Would be better with a generic error says something went wrong

https://jam.dev/c/1dcacc3d-34fa-494d-9369-19ba81b10eb9

**Review by popatre — CHANGES_REQUESTED** [review]
Nice optimistic rendering, however, your error doesnt seem to reset. 

You get it appearing again if its already appeared, and actually shows up twice, despite it working when online

https://jam.dev/c/31710fcd-e70e-480d-9646-d355e1596e96

**Review by ghost — APPROVED** [review]
Your voting works great, on a slow connection and offline. I'd reconsider the use of an alert as they do take the user out of the flow. You could conditionally render an error message as an example. However this is a suggestion not a requirement.

**Pull request merged**
